export enum CheckoutLocators {
    CHECKOUT_BUTTON = 'a.btn.btn-default.check_out',
    CART_PRICES = 'p.cart_total_price',
    PRODUCT_UNITARY_PRICE = 'td.cart_price',
    PRODUCT_QUANTITY = 'td.cart_quantity',
    PRODUCT_SUBTOTAL = 'td.cart_subtotal',
    CONFIRM_ORDER_BUTTON = 'a.btn.btn-default.confirm_order',
    TERMS_BUTTON = 'a.btn.btn-default.terms',
    FINAL_CONFIRM_BUTTON = 'a.btn.btn-default.final_confirm',
    ADD_TO_CART_BUTTON = '.add-to-cart',
    ADD_TO_CART_ID = 'a.add-to-cart',
    PRODUCT_ELEMENT = '.productinfo.text-center',
    PRODUCTS_INFO = '.features_items .col-sm-4',
    PRODUCT_PRICE = '.productinfo h2',
    PRODUCT_INFO = '.productinfo p',
    PRODUCT_ID = 'data-product-id',
    PROCEED_TO_CHECKOUT_BUTTON = 'a.check_out',
    NAME_ON_CARD = '[data-qa="name-on-card"]',
    CARD_NUMBER = '[data-qa="card-number"]',
    EXPIRY_MONTH = '[data-qa="expiry-month"]',
    EXPIRY_YEAR = '[data-qa="expiry-year"]',
    CVV = '[data-qa="cvc"]',
    PAYMENT_BUTTON = '[data-qa="pay-button"]',
    PLACE_ORDER_BUTTON = 'a.check_out[href="/payment"]',
    CART_TABLE_ROWS = 'tbody tr[id^="product-"]',
    CART_PRODUCT_NAME = 'td.cart_description h4 a',
    CART_PRODUCT_CATEGORY = 'td.cart_description p',
    CART_PRODUCT_PRICE = 'td.cart_price p',
    CART_PRODUCT_QUANTITY = 'td.cart_quantity button',
    CART_PRODUCT_TOTAL = 'td.cart_total p.cart_total_price',
    CART_TOTAL_AMOUNT = 'tbody tr:last-child td p.cart_total_price',
}
