export enum CheckoutLocators {
    ADD_TO_CART_BUTTON = '.add-to-cart',
    ADD_TO_CART_ID = 'a.add-to-cart',
    CARD_NUMBER = '[name="card_number"]',
    CART_PRODUCT_DESCRIPTION = 'td.cart_description p',
    CART_PRODUCT_NAME = 'td.cart_description h4 a',
    CART_PRODUCT_PRICE = 'td.cart_price p',
    CART_PRODUCT_QUANTITY = 'td.cart_quantity button',
    CART_PRODUCT_TOTAL = 'td.cart_total p.cart_total_price',
    CART_PRODUCT_TOTAL_AMOUNT = 'tbody tr:last-child td p.cart_total_price',
    CART_TABLE_ROW = 'tbody tr[id^="product-"]',
    CHECKOUT_BUTTON = 'Proceed To Checkout',
    CVV = '[name="cvc"]',
    EXPIRY_MONTH = '[name="expiry_month"]',
    EXPIRY_YEAR = '[name="expiry_year"]',
    INFO_HEADER_ORDER_PLACED = 'Order Placed!',
    NAME_ON_CARD = '[name="name_on_card"]',
    PAYMENT_BUTTON = 'Pay and Confirm Order',
    PLACE_ORDER = 'Place Order',
    PROCEED_TO_CHECKOUT = 'Proceed To Checkout',
    PRODUCT_ID = 'data-product-id',
    PRODUCT_INFO = '.productinfo p',
    PRODUCT_PRICE = '.productinfo h2',
    PRODUCT_QUANTITY = 'td.cart_quantity',
    PRODUCTS_CARD_INFO = '.single-products',
};
