export enum CheckoutLocators {
    ADD_TO_CART_BUTTON_CSS = '.add-to-cart',
    ADD_TO_CART_LINK_CSS = 'a.add-to-cart',
    CARD_NUMBER_INPUT_CSS = '[name="card_number"]',
    CART_PRODUCT_DESCRIPTION_CSS = 'td.cart_description p',
    CART_PRODUCT_NAME_LINK_CSS = 'td.cart_description h4 a',
    CART_PRODUCT_PRICE_CSS = 'td.cart_price p',
    CART_PRODUCT_QUANTITY_BUTTON_CSS = 'td.cart_quantity button',
    CART_PRODUCT_TOTAL_CSS = 'td.cart_total p.cart_total_price',
    CART_TABLE_ROW_CSS = 'tbody tr[id^="product-"]',
    CART_TOTAL_AMOUNT_CSS = 'tbody tr:last-child td p.cart_total_price',
    CHECKOUT_LINK = 'Proceed To Checkout',
    CVV_INPUT_CSS = '[name="cvc"]',
    EXPIRY_MONTH_INPUT_CSS = '[name="expiry_month"]',
    EXPIRY_YEAR_INPUT_CSS = '[name="expiry_year"]',
    NAME_ON_CARD_INPUT_CSS = '[name="name_on_card"]',
    ORDER_PLACED_HEADER = 'Order Placed!',
    PAYMENT_BUTTON = 'Pay and Confirm Order',
    PLACE_ORDER_LINK = 'Place Order',
    PROCEED_TO_CHECKOUT_TEXT = 'Proceed To Checkout',
    PRODUCT_CARD_INFO_CSS = '.single-products',
    PRODUCT_ID_ATTR = 'data-product-id',
    PRODUCT_INFO_CSS = '.productinfo p',
    PRODUCT_PRICE_CSS = '.productinfo h2',
    PRODUCT_QUANTITY_CSS = 'td.cart_quantity',
};
