export enum LoginLocators {
    ACCOUNT_CREATED_HEADER = 'Account Created!',
    ACCOUNT_DELETED_HEADER = 'Account Deleted!',
    ADDRESS_INPUT = 'Address',
    CITY_INPUT = 'City',
    COMPANY_INPUT = 'Company',
    CONTINUE_BUTTON = 'Continue',
    COUNTRY_SELECT = 'Country',
    CREATE_ACCOUNT_BUTTON = 'Create Account',
    DATE_DAY_SELECT = '#days',
    DATE_MONTH_SELECT = '#months',
    DATE_YEAR_SELECT = '#years',
    EMAIL_INPUT = 'Email Address',
    FIRST_NAME_INPUT = 'First name',
    GENDER_FEMALE_RADIO = 'Mrs.',
    GENDER_MALE_RADIO = 'Mr.',
    LAST_NAME_INPUT = 'Last name',
    LOGIN_BUTTON = 'Login',
    LOGIN_ERROR_MESSAGE = 'Your email or password is incorrect!',
    LOGIN_HEADER = 'Login to your account',
    MOBILE_NUMBER_INPUT = 'Mobile Number',
    NAME_INPUT = 'Name',
    PASSWORD_INPUT = 'Password',
    SIGNUP_BUTTON = 'Signup',
    SIGNUP_LOGIN_LINK = 'Signup / Login',
    STATE_INPUT = 'State',
    ZIPCODE_INPUT = '#zipcode',
};
