export enum LoginLocators {
    ADDRESS = 'Address',
    CITY = 'City',
    COMPANY = 'Company',
    CONTINUE_BUTTON = 'Continue',
    COUNTRY = 'Country',
    CREATE_ACCOUNT_BUTTON = 'Create Account',
    DATE_DAY = '#days',
    DATE_MONTH = '#months',
    DATE_YEAR = '#years',
    EMAIL_ADDRESS = 'Email Address',
    FIRST_NAME = 'First name',
    GENDER_FEMALE = 'Mrs.',
    GENDER_MALE = 'Mr.',
    HEADER_ACCOUNT_CREATED = 'Account Created!',
    HEADER_ACCOUNT_DELETED = 'Account Deleted!',
    LAST_NAME = 'Last name',
    LOGIN_BUTTON = 'Login',
    LOGIN_ERROR_MESSAGE = 'Your email or password is incorrect!',
    LOGIN_HEADER = 'Login to your account',
    MOBILE_NUMBER = 'Mobile Number',
    NAME = 'Name',
    PASSWORD = 'Password',
    SIGNUP_BUTTON = 'Signup',
    SIGNUP_LOGIN_BUTTON = 'Signup / Login',
    STATE = 'State',
    ZIPCODE = '#zipcode',
};
