export enum LoginLocators {
    SIGNUP_LOGIN_BUTTON = 'text=Signup / Login',
    LOGIN_HEADER = 'h2:has-text("Login to your account")',
    EMAIL_INPUT = 'input[data-qa="login-email"]',
    PASSWORD_INPUT = 'input[data-qa="login-password"]',
    LOGIN_BUTTON = 'button[data-qa="login-button"]',
    LOGIN_ERROR_MESSAGE = 'p:has-text("Your email or password is incorrect!")',
    SIGNUP_NAME = 'input[data-qa="signup-name"]',
    SIGNUP_EMAIL = 'input[data-qa="signup-email"]',
    SIGNUP_PASSWORD = '[data-qa="password"]',
    SIGNUP_BUTTON = 'button[data-qa="signup-button"]',
    GENDER_MALE = 'input[value="Mr"]',
    GENDER_FEMALE = 'input[value="Mrs"]',
    DATE_DAY = '#days',
    DATE_MONTH = '#months',
    DATE_YEAR = '#years',
    FIRST_NAME = 'input[data-qa="first_name"]',
    LAST_NAME = 'input[data-qa="last_name"]',
    COMPANY = 'input[data-qa="company"]',
    ADDRESS = 'input[data-qa="address"]',
    COUNTRY = '#country',
    STATE = 'input[data-qa="state"]',
    CITY = 'input[data-qa="city"]',
    ZIPCODE = 'input[data-qa="zipcode"]',
    MOBILE_PHONE = 'input[data-qa="mobile_number"]',
    CREATE_ACCOUNT_BUTTON = 'button[data-qa="create-account"]',
    CONTINUE_BUTTON = '[data-qa="continue-button"]',
};
