export enum ProductsLocators {
    PRODUCTS_HEADER = 'h2.title.text-center',
    SEARCH_INPUT = 'input[id="search_product"]',
    SEARCH_BUTTON = 'button[id="submit_search"]',
    NO_PRODUCTS_FOUND_MESSAGE = 'p:has-text("No products found")',
    WOMENS_PRODUCTS = 'a[href="#Women"]',
    WOMENS_PRODUCTS_DRESSES = 'a[href="/category_products/1"]',
    WOMENS_PRODUCTS_TSHIRTS = 'a[href="/category_products/2"]',
    WOMENS_PRODUCTS_SAREE = 'a[href="/category_products/7"]',
    MENS_PRODUCTS = 'a[href="#Men"]',
    MENS_PRODUCTS_TSHIRTS = 'a[href="/category_products/3"]',
    MENS_PRODUCTS_JEANS = 'a[href="/category_products/6"]',
    KIDS_PRODUCTS = 'a[href="#Kids"]',
    KIDS_PRODUCTS_KIDS_DRESS = 'a[href="/category_products/4"]',
    KIDS_PRODUCTS_KIDS_TOYS = 'a[href="/category_products/5"]',
    BRAND_POLO = 'a[href="/brand_products/Polo"]',
    BRAND_HM = 'a[href="/brand_products/H&M"]',
    BRAND_MADAME = 'a[href="/brand_products/Madame"]',
    BRAND_MAST_HARBOUR = 'a[href="/brand_products/Mast & Harbour"]',
    BRAND_BABYHUG = 'a[href="/brand_products/Babyhug"]',
    BRAND_BIBA = 'a[href="/brand_products/Biba"]',
    BRAND_ALLEN_SOLLY_JUNIOR = 'a[href="/brand_products/Allen Solly Junior"]',
    BRAND_KOKIE_KIDS = 'a[href="/brand_products/Kookie Kids"]',
    PRODUCT_BRAND_GRID = "PRODUCT_BRAND",
    VIEW_PRODUCT_FIRST_LINK = 'a[href="/product_details/1"]:has-text("View Product")',
    PRODUCT_INFO_GRID = '.productinfo.text-center',
    PRODUCT_NAME_GRID = '.productinfo.text-center p',
    PRODUCT_PRICE_GRID = '.productinfo.text-center h2',
    ADD_TO_CART_BUTTON_GRID = '.btn.add-to-cart',
    VIEW_PRODUCT_LINK = 'a[href^="/product_details/"]',
    PRODUCT_WRAPPER = '.product-image-wrapper',
    PRODUCT_ITEM = '.col-sm-4:has(.product-image-wrapper)',
    WRITE_REVIEW_TAB = 'a:has-text("Write Your Review")',
    REVIEWS_TAB = 'a[href="#reviews"][data-toggle="tab"]',
    PRODUCT_INFORMATION = '.product-information',
    PRODUCT_CATEGORY = '.product-information p:has-text("Category:")',
    PRODUCT_PRICE = '.product-information span span:first-child',
    PRODUCT_AVAILABILITY = '.product-information p:has-text("Availability:")',
    PRODUCT_CONDITION = '.product-information p:has-text("Condition:")',
    PRODUCT_BRAND = '.product-information p:has-text("Brand:")',
    QUANTITY_INPUT = 'input#quantity',
    ADD_TO_CART_BUTTON = 'button.btn.cart',
    PRODUCT_NAME = '.product-information h2',
    SEARCHED_PRODUCTS_HEADER = 'h2.title:has-text("Searched Products")',
    SELECT_PRODUCTS_BRAND_POLO_HEADER = 'h2.title:has-text("Brand - Polo Products")',
}